modLoader="lowcodefml" #mandatory
loaderVersion="[44,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
description='''
Allows modpacks to add Datapacks & Resource Packs
'''
[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"
