modLoader="lowcodefml" #mandatory
loaderVersion="[1,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
description='''
Allows modpacks to add Datapacks & Resource Packs
'''

[[mixins]]
config = "globalpacks.mixins.json"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,)"
    ordering="NONE"
    side="BOTH"
