modLoader="lowcodefml" #mandatory
loaderVersion="[44,45]" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="globalpacks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Global Packs" #mandatory
description='''
Allows modpacks to add Datapacks & Resource Packs
'''
[[dependencies.globalpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"
